const root=document.documentElement;const themeToggle=document.getElementById('themeToggle');const menuToggle=document.querySelector('.menu-toggle');const navLinks=document.querySelector('.nav-links');const savedTheme=localStorage.getItem('minhaz-theme');if(savedTheme)root.setAttribute('data-theme',savedTheme);
const syncThemeToggle=()=>{const dark=root.getAttribute('data-theme')==='dark';themeToggle?.setAttribute('aria-pressed',String(dark));themeToggle?.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme')};syncThemeToggle();
themeToggle?.addEventListener('click',()=>{const next=root.getAttribute('data-theme')==='dark'?'light':'dark';root.setAttribute('data-theme',next);localStorage.setItem('minhaz-theme',next);syncThemeToggle()});
const setMenuState=open=>{navLinks?.classList.toggle('open',open);menuToggle?.setAttribute('aria-expanded',String(open));menuToggle?.setAttribute('aria-label',open?'Close menu':'Open menu')};
menuToggle?.addEventListener('click',()=>setMenuState(!navLinks?.classList.contains('open')));
const serviceLink=navLinks?.querySelector('a[href="/services/"]');
if(serviceLink){const silo=document.createElement('div');silo.className='service-silo';silo.innerHTML='<button class="silo-trigger" type="button" aria-expanded="false">SEO Services <span class="silo-arrow">▾</span></button><div class="silo-panel"><div class="silo-group"><p class="silo-title">Core SEO</p><a href="/services/technical-seo/">Technical SEO</a><a href="/services/on-page-seo/">On-Page SEO</a><a href="/services/local-seo/">Local SEO</a><a href="/services/seo-audits/">SEO Audit</a></div><div class="silo-group"><p class="silo-title">Research</p><a href="/insights/keyword-research/">Keyword Research</a><a href="/insights/content-seo/">Content SEO</a><a href="/insights/competitive-analysis/">Competitor Analysis</a></div><div class="silo-group"><p class="silo-title">Authority</p><a href="/services/off-page-seo/">Off-Page SEO</a><a href="/insights/backlink-analysis/">Backlink Analysis</a><a href="/services/local-seo/#citations">Citations &amp; GBP</a></div><div class="silo-group"><p class="silo-title">AI Search</p><a href="/services/ai-search-seo/">AI Search SEO</a><a href="/services/aeo/">AEO</a><a href="/services/geo/">GEO</a></div></div>';serviceLink.replaceWith(silo);const trigger=silo.querySelector('.silo-trigger');trigger?.addEventListener('click',()=>{const open=silo.classList.toggle('open');trigger.setAttribute('aria-expanded',String(open))});silo.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{silo.classList.remove('open');navLinks?.classList.remove('open')}));document.addEventListener('click',e=>{if(!silo.contains(e.target)){silo.classList.remove('open');trigger?.setAttribute('aria-expanded','false')}})}
navLinks?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenuState(false)));
const form=document.getElementById('seoContactForm');const status=document.getElementById('formStatus');form?.addEventListener('submit',e=>{const captcha=form.querySelector('textarea[name="h-captcha-response"]');if(!captcha||!captcha.value){e.preventDefault();if(status)status.textContent='Please complete the human verification before submitting.'}});

/* SEO structured data: one generated JSON-LD node per page. Existing FAQPage markup is preserved. */
(()=>{const base='https://niazmahmudminhaz.github.io';const person={"@type":"Person","@id":base+'/#person',name:'Niaz Mahmud Minhaz',jobTitle:'SEO Consultant',url:base+'/',image:base+'/assets/niaz-mahmud-minhaz-best-seo-consultant-in-dhaka.webp',address:{"@type":'PostalAddress',addressLocality:'Dhaka',addressCountry:'BD'},email:'mailto:niazmahmud4368@gmail.com',knowsAbout:['Technical SEO','Local SEO','On-Page SEO','SEO audits','Keyword research','Content SEO','Off-Page SEO','Backlink analysis','AI Search SEO','AEO','GEO','Structured data','Search intent'],worksFor:{'@id':base+'/#service'}};const service={"@type":'ProfessionalService',"@id":base+'/#service',name:'Niaz Mahmud Minhaz — SEO Consulting',description:'SEO consulting covering Technical SEO, On-Page SEO, Local SEO, SEO audits, Off-Page SEO, content SEO and AI search optimization (AEO/GEO).',url:base+'/',image:base+'/assets/niaz-mahmud-minhaz-best-seo-consultant-in-dhaka.webp',founder:{'@id':base+'/#person'},address:{"@type":'PostalAddress',addressLocality:'Dhaka',addressCountry:'BD'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},email:'mailto:niazmahmud4368@gmail.com',telephone:'+8801622184191',hasOfferCatalog:{"@type":'OfferCatalog',name:'SEO Services',itemListElement:['technical-seo','on-page-seo','local-seo','seo-audits','off-page-seo','ai-search-seo'].map((slug,i)=>({"@type":'Offer',itemOffered:{"@type":'Service',name:['Technical SEO','On-Page SEO','Local SEO','SEO Audit','Off-Page SEO','AI Search SEO'][i],url:base+'/services/'+slug+'/'}}))}};const website={"@type":'WebSite',"@id":base+'/#website',url:base+'/',name:'Niaz Mahmud Minhaz — SEO Consultant',publisher:{'@id':base+'/#person'},inLanguage:'en'};const breadcrumb=(items)=>({"@type":'BreadcrumbList',itemListElement:items.map((x,i)=>({"@type":'ListItem',position:i+1,name:x[0],item:x[1]}))});const homeCr=[['Home',base+'/']];const serviceCr=(name,url)=>[['Home',base+'/'],['Services',base+'/services/'],[name,url]];const pageSchemas={
'/about/':{"@context":'https://schema.org',"@type":'AboutPage',url:base+'/about/',name:'About Niaz Mahmud Minhaz | SEO Consultant in Dhaka',description:'Learn about Niaz Mahmud Minhaz, a Professional SEO Consultant in Bangladesh focused on Technical SEO, Local SEO, audits, search intent and data-driven strategy.',mainEntity:{'@id':base+'/#person'},breadcrumb:breadcrumb([['Home',base+'/'],['About',base+'/about/']])},
'/services/':{"@context":'https://schema.org',"@type":'CollectionPage',url:base+'/services/',name:'SEO Consultant Services in Bangladesh | Technical, Local & AI',description:'Explore SEO consultant services in Bangladesh including Technical SEO, On-Page SEO, Local SEO, SEO audits, Off-Page SEO, content SEO and AI search optimization.',breadcrumb:breadcrumb([['Home',base+'/'],['Services',base+'/services/']]),hasPart:['technical-seo','on-page-seo','local-seo','seo-audits','off-page-seo','ai-search-seo'].map((slug,i)=>({"@type":'Service',name:['Technical SEO','On-Page SEO','Local SEO','SEO Audit','Off-Page SEO','AI Search SEO'][i],url:base+'/services/'+slug+'/'}))},
'/services/technical-seo/':{"@context":'https://schema.org',"@type":'Service',name:'Technical SEO Consultant in Bangladesh | Technical SEO Audit',description:'Technical SEO consultant in Bangladesh helping businesses improve crawlability, indexability, Core Web Vitals, structured data and site architecture.',url:base+'/services/technical-seo/',serviceType:'Technical SEO',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},breadcrumb:breadcrumb(serviceCr('Technical SEO',base+'/services/technical-seo/'))},
'/services/on-page-seo/':{"@context":'https://schema.org',"@type":'Service',name:'On Page SEO Expert in Bangladesh | Content & Search Intent',description:'Work with an On Page SEO Expert for keyword mapping, content SEO, search intent, internal linking, titles, meta descriptions and website relevance.',url:base+'/services/on-page-seo/',serviceType:'On-Page SEO',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},breadcrumb:breadcrumb(serviceCr('On-Page SEO',base+'/services/on-page-seo/'))},
'/services/local-seo/':{"@context":'https://schema.org',"@type":'Service',name:'Local SEO Consultant in Bangladesh | Google Business Profile',description:'Local SEO consultant in Bangladesh helping businesses improve local search visibility with Google Business Profile, citations and local content.',url:base+'/services/local-seo/',serviceType:'Local SEO',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Bangladesh'},breadcrumb:breadcrumb(serviceCr('Local SEO',base+'/services/local-seo/'))},
'/services/seo-audits/':{"@context":'https://schema.org',"@type":'Service',name:'SEO Audit Consultant in Bangladesh | Complete Website SEO Audit',description:'SEO audit consultant in Bangladesh providing complete website audits covering technical, on-page, content, local and authority issues with prioritized actions.',url:base+'/services/seo-audits/',serviceType:'SEO Audit',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},breadcrumb:breadcrumb(serviceCr('SEO Audit',base+'/services/seo-audits/'))},
'/services/off-page-seo/':{"@context":'https://schema.org',"@type":'Service',name:'Off-Page SEO Consultant in Bangladesh | Backlink Analysis',description:'Explore Off-Page SEO, backlink analysis, ethical link strategy and citation support for businesses seeking stronger authority and search visibility in Bangladesh.',url:base+'/services/off-page-seo/',serviceType:'Off-Page SEO',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},breadcrumb:breadcrumb(serviceCr('Off-Page SEO',base+'/services/off-page-seo/'))},
'/services/ai-search-seo/':{"@context":'https://schema.org',"@type":'Service',name:'AI Search SEO Consultant | AEO & GEO Strategy Bangladesh',description:'Improve visibility across AI search with AI Search SEO, AEO and GEO strategies built around helpful content, entities, structured data and answer-focused relevance.',url:base+'/services/ai-search-seo/',serviceType:'AI Search SEO',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},breadcrumb:breadcrumb(serviceCr('AI Search SEO',base+'/services/ai-search-seo/'))},
'/services/aeo/':{"@context":'https://schema.org',"@type":'Service',name:'AEO Consultant | Answer Engine Optimization | Niaz Mahmud Minhaz',description:'Explore Answer Engine Optimization strategies covering direct answers, question-led content, entities, structured data and search intent.',url:base+'/services/aeo/',serviceType:'Answer Engine Optimization',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},breadcrumb:breadcrumb(serviceCr('AEO',base+'/services/aeo/'))},
'/services/geo/':{"@context":'https://schema.org',"@type":'Service',name:'GEO Consultant | Generative Engine Optimization | Niaz Mahmud Minhaz',description:'Explore Generative Engine Optimization strategies using entities, evidence, structured information, useful content and AI search readiness.',url:base+'/services/geo/',serviceType:'Generative Engine Optimization',provider:{'@id':base+'/#service'},areaServed:{"@type":'Place',name:'Global (remote SEO consulting)'},breadcrumb:breadcrumb(serviceCr('GEO',base+'/services/geo/'))},
'/certifications/':{"@context":'https://schema.org',"@type":'ProfilePage',url:base+'/certifications/',name:'SEO Certifications | Niaz Mahmud Minhaz',mainEntity:{'@id':base+'/#person',hasCredential:{"@type":'EducationalOccupationalCredential',credentialCategory:'certificate',name:'Google Analytics Certification',recognizedBy:{"@type":'Organization',name:'Google Skillshop'},url:'https://skillshop.credential.net/profile/niazmahmud/wallet'}},breadcrumb:breadcrumb([['Home',base+'/'],['Certifications',base+'/certifications/']])},
'/contact/':{"@context":'https://schema.org',"@type":'ContactPage',url:base+'/contact/',name:'Request an SEO Consultation | Niaz Mahmud Minhaz',mainEntity:{'@id':base+'/#service'},breadcrumb:breadcrumb([['Home',base+'/'],['Contact',base+'/contact/']])},
'/case-studies/':{"@context":'https://schema.org',"@type":'CollectionPage',url:base+'/case-studies/',name:'SEO Case Studies | Niaz Mahmud Minhaz',description:'Explore SEO case studies, first-party website analysis, audit methodology and transparent evidence from Niaz Mahmud Minhaz.',breadcrumb:breadcrumb([['Home',base+'/'],['Case Studies',base+'/case-studies/']])},
'/insights/':{"@context":'https://schema.org',"@type":'CollectionPage',url:base+'/insights/',name:'SEO Insights | Keyword Research, Content SEO & AI Search',breadcrumb:breadcrumb([['Home',base+'/'],['Insights',base+'/insights/']])},
'/insights/keyword-research/':{"@context":'https://schema.org',"@type":'Article',headline:'Keyword Research for SEO | Search Intent & Keyword Mapping',description:'Learn practical keyword research, search intent, long-tail mapping and page targeting from an SEO consultant in Bangladesh.',url:base+'/insights/keyword-research/',author:{'@id':base+'/#person'},publisher:{'@id':base+'/#person'},breadcrumb:breadcrumb([['Home',base+'/'],['Insights',base+'/insights/'],['Keyword Research',base+'/insights/keyword-research/']])},
'/insights/content-seo/':{"@context":'https://schema.org',"@type":'Article',headline:'Content SEO Strategy | Search Intent & Topical Relevance',description:'Learn how content SEO connects search intent, topical relevance, internal linking and useful website content with an SEO consultant in Bangladesh.',url:base+'/insights/content-seo/',author:{'@id':base+'/#person'},publisher:{'@id':base+'/#person'},breadcrumb:breadcrumb([['Home',base+'/'],['Insights',base+'/insights/'],['Content SEO',base+'/insights/content-seo/']])},
'/insights/competitive-analysis/':{"@context":'https://schema.org',"@type":'Article',headline:'Competitive Analysis for SEO | Competitor Research Bangladesh',description:'Learn how SEO competitive analysis can identify SERP patterns, content gaps, backlink opportunities and page-level opportunities.',url:base+'/insights/competitive-analysis/',author:{'@id':base+'/#person'},publisher:{'@id':base+'/#person'},breadcrumb:breadcrumb([['Home',base+'/'],['Insights',base+'/insights/'],['Competitive Analysis',base+'/insights/competitive-analysis/']])},
'/insights/backlink-analysis/':{"@context":'https://schema.org',"@type":'Article',headline:'Backlink Analysis Guide | Off-Page SEO Bangladesh',description:'Learn backlink analysis, referring-domain quality, competitor link gaps and ethical off-page SEO strategy for websites in Bangladesh.',url:base+'/insights/backlink-analysis/',author:{'@id':base+'/#person'},publisher:{'@id':base+'/#person'},breadcrumb:breadcrumb([['Home',base+'/'],['Insights',base+'/insights/'],['Backlink Analysis',base+'/insights/backlink-analysis/']])},
'/insights/choose-an-seo-consultant/':{"@context":'https://schema.org',"@type":'Article',headline:'How to Choose an SEO Consultant | Bangladesh SEO Guide',description:'Learn how to choose an SEO consultant for WordPress, Shopify, Wix, e-commerce, local businesses, law firms and dental practices.',url:base+'/insights/choose-an-seo-consultant/',author:{'@id':base+'/#person'},publisher:{'@id':base+'/#person'},breadcrumb:breadcrumb([['Home',base+'/'],['Insights',base+'/insights/'],['How to Choose an SEO Consultant',base+'/insights/choose-an-seo-consultant/']])}
};const path=window.location.pathname.replace(/index\.html$/,'');if(path==='/'||path===''){document.querySelectorAll('script[type="application/ld+json"]').forEach(s=>s.remove());const s=document.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify({"@context":'https://schema.org',"@graph":[person,service,website]});document.head.appendChild(s)}else if(path!=='/faq/'&&pageSchemas[path]){document.querySelectorAll('script[type="application/ld+json"]').forEach(s=>s.remove());const s=document.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify(pageSchemas[path]);document.head.appendChild(s)}})();